### PR TITLE
Feature/sign up

### PR DESCRIPTION
**Pull request by Giticam**

### CODE REVIEW

**Comment by Giticam** [comment]
@jennli @tkbeili Please review the code.

**Comment by stanleylhs** [comment]
I refactored with "config.include FactoryGirl::Syntax::Methods" to get rid of the Factory Girl prefix.

**Comment by tkbeili** [comment]
This PR can't be merged automatically so I can't review it, make sure to rebase this branch and then force push so I can review

**Comment by stanleylhs** [comment]
@tkbeili Integration somehow changed as PR #4 and #6  got in before #3, but this #3 was the earlier pull request. Anyway this is now fixed.

**Comment by cerize** [comment]
:+1:

**Comment by stanleylhs** [comment]
Wait. So this PR is only 4 lines of code now???? LOL

**Comment by tkbeili** [comment]
Just merge this one for now. I will take a look at integration and give some feedback.

**Pull request merged**
